name: Test Self-Hosted Runner

on:
  push:
    branches: [ feature/integrate-sidebar-layout ]
  workflow_dispatch:

jobs:
  test-runner:
    name: Test Containerd Runner Connection
    runs-on: [self-hosted, linux, x64, kubernetes]
    
    steps:
    - name: Check runner info
      run: |
        echo "Runner name: ${{ runner.name }}"
        echo "Runner OS: ${{ runner.os }}"
        echo "Runner arch: ${{ runner.arch }}"
        echo "Working directory: $(pwd)"
        echo "Available tools:"
        # Check containerd tools
        nerdctl --version || echo "nerdctl not found"
        containerd --version || echo "containerd not found"
        kubectl version --client || echo "kubectl not found"
        node --version || echo "Node not found"
        python3 --version || echo "Python not found"
    
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: List files
      run: |
        echo "Repository contents:"
        ls -la
        
    - name: Test containerd functionality
      run: |
        echo "Testing containerd functionality..."
        nerdctl ps || echo "nerdctl ps failed"
        nerdctl images || echo "nerdctl images failed"
        
    - name: Test kubectl functionality
      run: |
        echo "Testing kubectl functionality..."
        kubectl cluster-info || echo "kubectl cluster-info failed"
        kubectl get pods --all-namespaces || echo "kubectl get pods failed"
    
    - name: Success message
      run: echo "✅ Self-hosted containerd runner is working correctly!"