name: Test Current Runner Setup

on:
  push:
    branches: [ feature/integrate-sidebar-layout ]
  workflow_dispatch:

jobs:
  test-dependencies:
    name: Test All Dependencies
    runs-on: [self-hosted, playwright, e2e]
    
    steps:
    - name: System Info
      run: |
        echo "OS: $(lsb_release -d | cut -f2)"
        echo "Python: $(python3 --version)"
        echo "Node.js: $(node --version)"
        echo "npm: $(npm --version)"
        
    - name: Test Python Tools
      run: |
        python3 --version
        pip --version || pip3 --version
        pytest --version
        black --version
        flake8 --version
        mypy --version
        
    - name: Test Database Clients
      run: |
        mongosh --version
        psql --version
        
    - name: Test Cloud CLIs (Optional)
      run: |
        aws --version || echo "AWS CLI not installed"
        az --version || echo "Azure CLI not installed"
        gcloud --version || echo "Google Cloud CLI not installed"
        
    - name: Test DevOps Tools
      run: |
        kubectl version --client || echo "kubectl not installed"
        terraform --version || echo "terraform not installed"
        gh --version || echo "GitHub CLI not installed"
        
    - name: Test Container Tools
      run: |
        docker --version || nerdctl --version
        docker info || nerdctl info || echo "Container runtime not working"
        
    - name: Test Build Tools
      run: |
        gcc --version || echo "gcc missing"
        make --version || echo "make missing"
        
    - name: Checkout and test project
      uses: actions/checkout@v4
      
    - name: Test Python project dependencies
      run: |
        pip install -r requirements/base.txt || echo "Failed to install base requirements"
        pip install -r requirements/test.txt || echo "Failed to install test requirements"
        
    - name: Test Node.js project dependencies  
      run: |
        cd src/react-frontend
        npm ci
        npx playwright install --dry-run
        
    - name: Success
      run: echo "🎉 All dependencies test complete!"